# Generated by Django 2.0.1 on 2018-10-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0016_remove_studentanswer_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.DateField(default='2018-10-12', max_length=12, null=True),
        ),
    ]
